### ISSUE TITLE
Share weights

### ISSUE THREAD

**Issue by stormxuwz** [kuza55/keras-extras#13]
I am not sure whether the script will make the weights shared. If not, simply split data into different towers will train each tower separately? 

For reference, in the tutorial https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py,
they have a (line 175) "tf.get_variable_scope().reuse_variables()" to make sure to reuse the weights. 

Thanks!

**Comment by vense** [comment]
I think make_parallel() may be sharing weight which tested in my experiment.

What about other people's thoughts?

**Comment by kuza55** [comment]
Keras shares weights when you call the same already constructed Layer on multiple tensors.
