### ISSUE TITLE
Is there a method to transform multiple-gpu model back to single-gpu model

### ISSUE THREAD

**Issue by TomHeaven** [kuza55/keras-extras#16]
I started to use the multiple-gpu method and found it speed-up training. However, how to convert the model back to single-gpu version since we may need to deploy the model on single-gpu machines?

**Comment by kuza55** [comment]
The weights are shared between original non-parallel model and the parallel model, so you should be able to save the original model to disk after training the parallel model, and then restore that model and it will run on a single GPU.

I'd be curious to hear more about your model where this is actually helping if you can share.

**Comment by TomHeaven** [comment]
That's brilliant! So I will provide a demo to end this issue. If we have a model defined in Keras named ``fcn``, the correct method to train it with multiple GPU and save in single GPU form is:
```python
if ngpus > 1:
    fcn_par = make_parallel(fcn, n_gpus=ngpus)
else:
    fcn_par = fcn
fcn_par.fit(x_train_noisy, y_train, epochs=iter_num, batch_size=batch_size, shuffle=True,
                    validation_data=(x_test, y_test))
fcn.save_weights('fcn.h5')
```
Then, we can load it in single GPU machines with
```
fcn.load_weights('fcn.h5')
```
